version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/reporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/reporter-cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/reporter-ffi"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/servermock"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/servermock-ffi"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tests-ffi"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
