FROM debian:latest

RUN apt-get update && \
    apt-get install -y \
    curl \
    tar \
    xz-utils \
    gcc \
    g++ \
    make \
    git \
    clang \
    llvm-dev

# install Zig
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "aarch64" ]; then \
    ZIG_ARCH="aarch64"; \
    else \
    ZIG_ARCH="x86_64"; \
    fi && \
    curl -L https://ziglang.org/download/0.15.2/zig-${ZIG_ARCH}-linux-0.15.2.tar.xz -o /tmp/zig.tar.xz && \
    tar -xf /tmp/zig.tar.xz -C /opt && \
    ln -s /opt/zig-${ZIG_ARCH}-linux-0.15.2/zig /usr/local/bin/zig && \
    rm /tmp/zig.tar.xz

WORKDIR /workspace
COPY . .

RUN mkdir -p zig-out/lib
RUN zig build --seed 0x00000000
RUN zig build test --seed 0x00000000

RUN echo "Passed."

WORKDIR /workspace
