name: CI

on:
  pull_request:

jobs:
  ci_build:
    name: (CI) Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.24.1'

      - run: cargo build
      - run: cargo test

      - run: go build
        working-directory: tests-ffi-go
      - run: go test
        working-directory: tests-ffi-go
        
