name: CI

on:
  pull_request:

jobs:
  ci_build:
    name: (CI) Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: cargo build --target x86_64-unknown-linux-gnu
      - run: cargo test
