name: CI

on:
  pull_request:

jobs:
  ci_build:
    name: (CI) Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: |
          docker build -t greener-reporter-zig:latest .

      - name: Create output directory
        run: mkdir -p ./zig-out/lib

      - name: Copy to host
        run: |
          docker run --name zig-builder greener-reporter-zig:latest
          docker cp zig-builder:/output/. ./zig-out/lib/

      - name: Build Rust part
        run: cargo build

      - name: Copy lib files
        run: |
          cp zig-out/lib/* tests-ffi/
          cp zig-out/lib/* target/debug/

      - name: Run Rust tests
        run: cargo test
